spring:
  application:
    name: sw-auth-service
  datasource:
    url: jdbc:postgresql://sw-auth-service-db:5432/postgres
    username: sw-auth-service-admin
    password: xNS893ntp1Tx918Y49y
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: m6pG:7)jalI2Ig`ZpU5Q^1`
      expirationHours: 24
